In [1]:
# TensorFlow and tf.keras
import tensorflow as tf

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

2.11.0


In [2]:
fashion_mnist = tf.keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4422102/4422102 [==============================] - 1s 0us/step


In [3]:
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

In [4]:
train_images.shape

(60000, 28, 28)

In [5]:

# data of first image
train_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,
          0,   0,  13,  73,   0,   0,   1,   4,   0,   0,   0,   0,   1,
          1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
          0,  36, 136, 127,  62,  54,   0,   0,   0,   1,   3,   4,   0,
          0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0, 102, 204, 176, 134, 144, 123,  23,   0,   0,   0,   0,  12,
         10,   0],
       [  

In [6]:
len(train_labels)

60000

In [7]:
train_labels

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [8]:
train_labels

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [9]:
test_images.shape

(10000, 28, 28)

In [10]:
len(test_labels)

10000

In [12]:
# what is maximum value in train image array
train_images[0].max()

255

In [13]:
# what is minimum value in train image array
train_images[0].min()

0

In [15]:
# Scale these values to a range of 0 to 1
train_images = train_images / 255.0

test_images = test_images / 255.0

In [17]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28),name='Input_Layer'),
    tf.keras.layers.Dense(128, activation='relu',name='Hidden_Layer'),
    tf.keras.layers.Dense(10,activation='softmax',name='Output_Layer')
])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Input_Layer (Flatten)       (None, 784)               0         
                                                                 
 Hidden_Layer (Dense)        (None, 128)               100480    
                                                                 
 Output_Layer (Dense)        (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [19]:

# train the model with batch size of 16, default batch size is 32
model.fit(train_images, train_labels, epochs=100, verbose=1, batch_size=16)

Epoch 1/100


C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\keras\backend.py:5585: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


3750/3750 [==============================] - 8s 2ms/step - loss: 0.9433 - accuracy: 0.6902
Epoch 2/100
3750/3750 [==============================] - 6s 2ms/step - loss: 0.5916 - accuracy: 0.7857
Epoch 3/100
3750/3750 [==============================] - 7s 2ms/step - loss: 0.5250 - accuracy: 0.8131
Epoch 4/100
3750/3750 [==============================] - 7s 2ms/step - loss: 0.4903 - accuracy: 0.8270
Epoch 5/100
3750/3750 [==============================] - 7s 2ms/step - loss: 0.4670 - accuracy: 0.8356
Epoch 6/100
3750/3750 [==============================] - 7s 2ms/step - loss: 0.4506 - accuracy: 0.8415
Epoch 7/100
3750/3750 [==============================] - 7s 2ms/step - loss: 0.4388 - accuracy: 0.8448
Epoch 8/100
3750/3750 [==============================] - 7s 2ms/step - loss: 0.4278 - accuracy: 0.8490
Epoch 9/100
3750/3750 [==============================] - 7s 2ms/step - loss: 0.4193 - accuracy: 0.8525
Epoch 10/100
3750/3750 [==============================] - 7s 2ms/step - loss: 0.4119 

Epoch 80/100
3750/3750 [==============================] - 6s 2ms/step - loss: 0.2500 - accuracy: 0.9099
Epoch 81/100
3750/3750 [==============================] - 7s 2ms/step - loss: 0.2492 - accuracy: 0.9100
Epoch 82/100
3750/3750 [==============================] - 7s 2ms/step - loss: 0.2486 - accuracy: 0.9104
Epoch 83/100
3750/3750 [==============================] - 7s 2ms/step - loss: 0.2477 - accuracy: 0.9107
Epoch 84/100
3750/3750 [==============================] - 7s 2ms/step - loss: 0.2462 - accuracy: 0.9115
Epoch 85/100
3750/3750 [==============================] - 7s 2ms/step - loss: 0.2452 - accuracy: 0.9118
Epoch 86/100
3750/3750 [==============================] - 7s 2ms/step - loss: 0.2434 - accuracy: 0.9134
Epoch 87/100
3750/3750 [==============================] - 6s 2ms/step - loss: 0.2428 - accuracy: 0.9129
Epoch 88/100
3750/3750 [==============================] - 7s 2ms/step - loss: 0.2421 - accuracy: 0.9136
Epoch 89/100
3750/3750 [==============================] - 6s 2ms